### ISSUE TITLE
Fails to compile with Xcode 7.1

### ISSUE THREAD

**Issue by wilkowski** [Citrrus/MBContactPicker#95]
use of undeclared identifier '_focused' in MBContactCollectionViewContactCell.m, line 87.  I'm using the podfile for installation.

**Comment by wilkowski** [comment]
Wasn't updated to latest version
